--- #YAML:1.0
name:               upfiles
version:            7
abstract:           Upload files to a remote FTP server.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::SQLite:         0
    DBI:                 0
    File::HomeDir:       0
    Locale::TextDomain:  0
    Math::Round:         0
    perl:                5.010
    URI:                 0
resources:
    homepage:  http://user42.tuxfamily.org/upfiles/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
        - xt
        - devel
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
